<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
    <style>
      .none {
        display: none;
      }
    </style>
    <div class="right_col" role="main">
      <div class="">
        <!-- 用户名单 start -->
        <div class="row x_title">
          <div class="col-md-6">
            <h3>用户名单</h3>
          </div>
        </div>
        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-9">
                  <div class="col-sm-1">
                    <label>
                      <input type="text" class="form-control input-sm" placeholder="用户ID">
                    </label>
                  </div>
                  <div class="col-sm-1">
                    <label>
                      <input type="text" class="form-control input-sm" placeholder="公司名称">
                    </label>
                  </div>
                  <a class="btn btn-primary btn-sm">
                    搜索
                  </a>
                </div>
                <div class="col-sm-3">
                  <div class="dataTables_filter">
                    <label>
                      <select class="form-control input-sm">
                        <option value="10">10</option>
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                      </select>
                    </label>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>用户ID</th>
                        <th>公司名称</th>
                        <th>短信类型</th>
                        <th>短信余额</th>
                        <th>操作</th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr>
                        <td style="line-height: 34px">1</td>
                        <td style="line-height: 34px">1</td>
                        <td style="line-height: 34px">1</td>
                        <td style="line-height: 34px">1</td>
                        <td>
                          <a class="btn btn-default btn-sm recharge" data-id="1">充值</a>
                          <a class="btn btn-default btn-sm rollback" data-id="1">回退</a>
                          <a class="btn btn-default btn-sm reset" data-id="1">重置密码</a>
                          <a class="btn btn-default btn-sm delete" data-id="1">帐号删除</a>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!-- 用户名单 end -->

        <div class="modal fade bs-example-modal-sm" id="rechargeModal">
          <div class="modal-dialog modal-sm" style="margin: 0;position: absolute;top: 40%;left: 50%;transform: translate(-40%,-50%);">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">充值</h4>
              </div>
              <div class="modal-body">
                <input type="text" name="recharge" class="form-control input-sm" placeholder="请输入充值数目">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="recharge">充值</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade bs-example-modal-sm" id="rollbackModal">
          <div class="modal-dialog modal-sm" style="margin: 0;position: absolute;top: 40%;left: 50%;transform: translate(-40%,-50%);">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">回退</h4>
              </div>
              <div class="modal-body">
                <input type="text" name="rollback" class="form-control input-sm" placeholder="请输入回退数目">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="rollback">回退</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade bs-example-modal-sm" id="resetModal">
          <div class="modal-dialog modal-sm" style="margin: 0;position: absolute;top: 40%;left: 50%;transform: translate(-40%,-50%);">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">重置密码</h4>
              </div>
              <div class="modal-body">
                <input type="text" name="reset" class="form-control input-sm" placeholder="请输入新密码">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="reset">重置密码</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade bs-example-modal-sm" id="deleteModal">
          <div class="modal-dialog modal-sm" style="margin: 0;position: absolute;top: 40%;left: 50%;transform: translate(-40%,-50%);">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="delTitle">身份确认</h4>
              </div>
              <div class="modal-body">
                <input type="text" name="surePwd" class="form-control input-sm" placeholder="请输入密码">
                <p class="none" id="rate">100%</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="deletePrev">下一步</button>
                <button type="button" class="btn btn-primary none" id="deleteSure">确定</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="/script/user/index.js"></script>
<?php $this->display("public/footer.phtml"); ?>