<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-6">
            <h3>用户名单</h3>
          </div>
        </div>
        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-9">
                    <span>用户</span>
                    <label>
                      <select class="form-control input-sm">
                        <option value="10">sss</option>
                        <option value="25">sss</option>
                        <option value="50">sss</option>
                      </select>
                    </label>
                    <span>账户类型</span>
                    <label>
                      <select class="form-control input-sm">
                        <option value="10">sss</option>
                        <option value="25">sss</option>
                        <option value="50">sss</option>
                      </select>
                    </label>
                    <span>操作类型</span>
                    <label>
                      <select class="form-control input-sm">
                        <option value="10">sss</option>
                        <option value="25">sss</option>
                        <option value="50">sss</option>
                      </select>
                    </label>
                    <div id="reportrange_right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc;display: inline-block;">
                      <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                      <span></span> <b class="caret"></b>
                    </div>
                  <a class="btn btn-primary btn-sm">
                    搜索
                  </a>
                </div>
                <div class="col-sm-3">
                  <div class="dataTables_filter">
                    <label>
                      <select class="form-control input-sm">
                        <option value="10">10</option>
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                      </select>
                    </label>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>用户ID</th>
                        <th>账户类型</th>
                        <th>操作类型</th>
                        <th>数量</th>
                        <th>时间</th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr>
                        <td style="line-height: 34px">1</td>
                        <td style="line-height: 34px">1</td>
                        <td style="line-height: 34px">1</td>
                        <td style="line-height: 34px">1</td>
                        <td style="line-height: 34px">2018.04.23 16:00:00</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
<?php echo $this->renderTpl('public/footer.phtml',array('addScript'=> array('/user/records.js')),'index');?>