<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
      <div class="right_col" role="main">
        <div class="">
          <!-- 用户名单 start -->
          <div class="row x_title">
            <div class="col-md-6">
              <h3>处理进度</h3>
            </div>
          </div>
          <div class="x_content">
            <div class="text-muted font-13 m-b-30">
              <div class="dataTables_wrapper dt-bootstrap no-footer">
                <div class="row">
                  <div class="col-sm-9">
                      <span>子账户</span>
                      <label>
                        <select class="form-control input-sm">
                          <option value="10">sss</option>
                          <option value="25">sss</option>
                          <option value="50">sss</option>
                        </select>
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="公司名称">
                      </label>
                      <span>短信类型</span>
                      <label>
                        <select class="form-control input-sm">
                          <option value="10">sss</option>
                          <option value="25">sss</option>
                          <option value="50">sss</option>
                        </select>
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="短信签名">
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="短信内容">
                      </label>
                      <div id="reportrange_right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc;display: inline-block;">
                        <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                        <span></span> <b class="caret"></b>
                      </div>
                    <a class="btn btn-primary btn-sm">
                      搜索
                    </a>
                  </div>
                  <div class="col-sm-3">
                    <div class="dataTables_filter">
                      <label>
                        <select class="form-control input-sm">
                          <option value="10">10</option>
                          <option value="25">25</option>
                          <option value="50">50</option>
                          <option value="100">100</option>
                        </select>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>用户ID</th>
                          <th>公司名称</th>
                          <th>号码归属地</th>
                          <th>号码数量</th>
                          <th>总提交数</th>
                          <th>总计费数</th>
                          <th>创建时间</th>
                          <th>短信类型</th>
                          <th>短信签名</th>
                          <th>短信内容</th>
                          <th>任务进度</th>
                        </tr>
                      </thead>

                      <tbody>
                        <tr>
                          <td style="line-height: 34px">1</td>
                          <td style="line-height: 34px">1</td>
                          <td style="line-height: 34px">1</td>
                          <td style="line-height: 34px">1</td>
                          <td style="line-height: 34px">1</td>
                          <td style="line-height: 34px">1</td>
                          <td style="line-height: 34px">1</td>
                          <td style="line-height: 34px">1</td>
                          <td style="line-height: 34px">1</td>
                          <td style="line-height: 34px">1</td>
                          <td style="line-height: 34px">1</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<?php $this->display("public/footer.phtml"); ?>