<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
    <div class="right_col" role="main">
      <div class="">
         <!-- 任务统计 start -->
        <div class="row x_title">
          <div class="col-md-6">
            <h3>任务统计</h3>
          </div>
        </div>
        <div class="row tile_count">
          <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-comments-o"></i>待处理任务</span>
            <div class="count green">1项</div>
          </div>
          <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-comments-o"></i>待审核模板</span>
            <div class="count green">2个</div>
          </div>
        </div>
        <!-- 任务统计 end -->

        <!-- 今日统计信息 start -->
        <div class="row x_title">
          <div class="col-md-6">
            <h3>今日统计</h3>
          </div>
        </div>
        <div class="row tile_count">
          <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-comments-o"></i>行业短信</span>
            <div class="count green">1000条</div>
            <span class="count_bottom">今日统计</span>
          </div>
          <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-comments-o"></i>营销短信</span>
            <div class="count green">1000条</div>
            <span class="count_bottom">今日统计</span>
          </div>
          <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-comments-o"></i>行业短信</span>
            <div class="count green">2000条</div>
            <span class="count_bottom">今日统计</span>
          </div>
          <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-comments-o"></i>营销短信</span>
            <div class="count green">2000条</div>
            <span class="count_bottom">今日统计</span>
          </div>
        </div>
        <!-- 今日统计信息 end -->
      </div>
    </div>
<?php $this->display("public/footer.phtml"); ?>