<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
      <div class="right_col" role="main">
        <div class="">
          <div class="row x_title">
            <div class="col-md-6">
              <h3>模板管理</h3>
            </div>
          </div>
          <div class="x_content">
            <div class="text-muted font-13 m-b-30">
              <div class="dataTables_wrapper dt-bootstrap no-footer">
                <div class="row">
                  <div class="col-sm-9">
                      <span>审核状态</span>
                      <label>
                        <select class="form-control input-sm">
                            <option value="0">全部</option>
                            <?php foreach ($this->templateStatus as $key =>$value):?>
                                <option value="<?php echo $key;?>" <?php echo $key==$this->status?'selected':'';?>><?php echo $value;?></option>
                            <?php endforeach;?>
                        </select>
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="签名">
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="模板内容">
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="用户ID">
                      </label>
                    <a class="btn btn-primary btn-sm">
                      搜索
                    </a>
                  </div>
                  <div class="col-sm-3">
                    <div class="dataTables_filter">
                      <label>
                        <select class="form-control input-sm">
                          <option value="10">10</option>
                          <option value="25">25</option>
                          <option value="50">50</option>
                          <option value="100">100</option>
                        </select>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>用户ID</th>
                          <th>公司名称</th>
                          <th>模板属性</th>
                          <th>模板类型</th>
                          <th>短信签名</th>
                          <th>模板内容</th>
                          <th>审核状态</th>
                          <th>原因</th>
                          <th>操作</th>
                        </tr>
                      </thead>
                      <?php if(!empty($this->pager->getList())):?>
                        <?php $mapper = \Mapper\UsersModel::getInstance();?>
                        <?php foreach ($this->pager->getList() as $key=>$value):?>
                          <tbody>
                            <tr>
                              <td style="line-height: 34px"><?php echo $mapper->getUsername($value['user_id']);?></td>
                              <td style="line-height: 34px"><?php echo $mapper->getName($value['user_id']);?></td>
                              <td style="line-height: 34px"><?php echo $this->accounts[$value['classify']]?></td>
                              <td style="line-height: 34px"><?php echo $this->types[$value['type']]?></td>
                              <td style="line-height: 34px"><?php echo $value['sign']?></td>
                              <td style="line-height: 34px;overflow: hidden;"><p style="width: 100px;cursor: pointer;" class="showcontent"><?php echo $value['content']?></p></td>
                              <td style="line-height: 34px"><?php echo $this->templateStatus[$value['status']]?></td>
                              <td style="line-height: 34px"><?php echo $value['reason']?></td>
                              <td>
                                <a class="btn btn-default btn-sm recharge">审核</a>
                              </td>
                            </tr>
                          </tbody>
                          <?php endforeach;?>
                      <?php else:?>
                          <tbody>
                          <tr><td colspan="16">没有找到用户</td></tr>
                          </tbody>
                      <?php endif;?>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal fade bs-example-modal-md" id="detailModal">
            <div class="modal-dialog modal-md" style="margin: 0;position: absolute;top: 40%;left: 50%;transform: translate(-40%,-50%);">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                  </button>
                  <h4 class="modal-title">模板详细内容</h4>
                </div>
                <div class="modal-body">
                  <textarea id="content" style="width: 100%"></textarea>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" id="close">确定</button>
                </div>
              </div>
            </div>
          </div>
          <div class="modal fade bs-example-modal-md" id="auditModal">
            <div class="modal-dialog modal-md" style="margin: 0;position: absolute;top: 40%;left: 50%;transform: translate(-40%,-50%);">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                  </button>
                  <h4 class="modal-title">审核操作</h4>
                </div>
                <div class="modal-body">
                  <form class="form-horizontal form-label-left" id="auditForm">
                  <div class="form-group">
                    <label class="control-label col-sm-3">审核结果</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <div class="radio col-md-3" style="padding-left: 0px; padding-right: 0px">
                        <label><input type="radio" name="audit" value="adopted" checked>通过</label>
                      </div>
                      <div class="radio col-md-3" style="padding-left: 0px; padding-right: 0px">
                        <label><input type="radio" name="audit" value="not_adopted ">不通过</label>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-sm-3">审核原因</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input type="text" name="id" value="1" hidden="">
                      <input name="reason" type="text" class="form-control" placeholder="请输入审核原因">
                    </div>
                    <div style="clear: both;overflow: hidden;"></div>
                    <p class="col-sm-offset-3" style="margin-top: 5px;padding-left: 11px;color: #d9534f;">若选择不通过，则审核原因必须输入</p>
                  </div>
                </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" id="audit">下一步</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <script src="/script/template/index.js"></script>
<?php $this->display("public/footer.phtml"); ?>